
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        let p=new Promise((resolve,reject)=>{
            setTimeout(()=>{
                resolve('ok');
               //reject('error')
            },1000);
        })
        p.then(value=>{
            return new Promise((resolve,reject)=>{
                resolve('success')
            })
        }).then(value=>{
            console.log(value); //success(因為這邊已經不是promise 所以下面會undefined)

            //如果要阻止往下跑的話 加上return 再new Promise狀態會變成pending 就不會往下跑了
            //return new Promise(()=>{}) //結果印 success

        }).then(value=>{
            console.log(value); //undefined
        }).catch(reason=>{
            console.log(reason); //異常穿透 只要裡面有錯誤就會跑到這裡
        })

        /*
        結果會印
        兩個then都會經過
        success
        undefined
        */

    </script>
</body>
</html>